# Introduction to Tensors

In [1]:
import torch

print(torch.__version__)


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/admin/Library/Caches/pypoetry/virtualenvs/generative-ai-zqkb-BGY-py3.12/lib/python3.12/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/Users/admin/Library/Caches/pypoetry/virtualenvs/generative-ai-zqkb-BGY-py3.12/lib/python3.12/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/Users/admin/Library/Caches/

2.2.2


**1. Scalar**

In [2]:
scalar: torch.Tensor = torch.tensor(data=8)

In [3]:
print(f"Scalar tensor: {scalar}")
print(f"Number of dimensions: {scalar.ndim} (0D tensor)")
print(f"Shape: {scalar.shape} (No dimensions for a scalar)")
print(f"Scalar value: {scalar.item()} (Extracted value)")
print(f"Element size: {scalar.element_size()} bytes (size of one element)")

Scalar tensor: 8
Number of dimensions: 0 (0D tensor)
Shape: torch.Size([]) (No dimensions for a scalar)
Scalar value: 8 (Extracted value)
Element size: 8 bytes (size of one element)


**2. Vector**

In [4]:
vector: torch.Tensor = torch.tensor(data=[8, 5])

In [5]:
print(f"Vector tensor: {vector}")
print(f"Number of dimensions: {vector.ndim} (1D tensor)")
print(f"Shape: {vector.shape} (Number of elements)")
print(f"Element size: {vector.element_size()} bytes (size of one element)")

Vector tensor: tensor([8, 5])
Number of dimensions: 1 (1D tensor)
Shape: torch.Size([2]) (Number of elements)
Element size: 8 bytes (size of one element)


**3. Matrix**

In [6]:
matrix: torch.Tensor = torch.tensor(data=[[1, 2], [3, 4], [4, 5]])

In [7]:
print(f"Matrix tensor:\n{matrix}")
print(f"Number of dimensions: {matrix.ndim} (2D tensor)")
print(f"Shape: {matrix.shape} (Rows, Columns)")
print(f"Element size: {matrix.element_size()} bytes (size of one element)")

Matrix tensor:
tensor([[1, 2],
        [3, 4],
        [4, 5]])
Number of dimensions: 2 (2D tensor)
Shape: torch.Size([3, 2]) (Rows, Columns)
Element size: 8 bytes (size of one element)


**4. Tensor**

In [8]:
tensor: torch.Tensor = torch.tensor(data=[[[1, 2, 3, 4], [3, 2, 1, 0], [4, 5, 6, 5]]])

In [9]:
print(f"Tensor:\n{tensor}")
print(f"Number of dimensions: {tensor.ndim} (Tensor rank)")
print(f"Shape: {tensor.shape} (Dimensions of the tensor)")
print(f"Element size: {tensor.element_size()} bytes (Size of each element)")

Tensor:
tensor([[[1, 2, 3, 4],
         [3, 2, 1, 0],
         [4, 5, 6, 5]]])
Number of dimensions: 3 (Tensor rank)
Shape: torch.Size([1, 3, 4]) (Dimensions of the tensor)
Element size: 8 bytes (Size of each element)


**5. Random Tensors**

In [10]:
random_tensor: torch.Tensor = torch.rand(size=(3, 4))
print(f"Random tensor:\n{random_tensor}")

Random tensor:
tensor([[0.7817, 0.8426, 0.7833, 0.5532],
        [0.8951, 0.9909, 0.3634, 0.7415],
        [0.2377, 0.4491, 0.4820, 0.5880]])


**6. Zeros and Ones**

In [11]:
zeros: torch.Tensor = torch.zeros(size=(3, 4))
print(f"Zeros tensor:\n{zeros}")

Zeros tensor:
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [12]:
ones: torch.Tensor = torch.ones(size=(3, 4))
print(f"Ones tensor:\n{ones}")

Ones tensor:
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


**7. Arange and Tensor Like**

In [13]:
x: torch.Tensor = torch.arange(start=0, end=10, step=1)
print(x)
y: torch.Tensor = torch.arange(start=0, end=10, step=2)
print(y)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 2, 4, 6, 8])


In [14]:
sample: torch.Tensor = torch.rand(size=(4, 2))
print(f"Sample tensor:\n{sample}")
print(f"Number of dimensions: {sample.ndim} (Tensor rank)")
print(f"Shape: {sample.shape} (Dimensions of the tensor)")
print(f"Element size: {sample.element_size()} bytes (Size of each element)")

Sample tensor:
tensor([[0.3092, 0.8780],
        [0.8937, 0.0450],
        [0.2632, 0.5114],
        [0.3763, 0.2236]])
Number of dimensions: 2 (Tensor rank)
Shape: torch.Size([4, 2]) (Dimensions of the tensor)
Element size: 4 bytes (Size of each element)


In [20]:
zeros_like: torch.Tensor = torch.zeros_like(input=sample)
print(f"Zeros tensor:\n{zeros_like}")
print(f"Diension: {zeros_like.ndim}")
print(f"Shape: {zeros_like.shape} (Dimensions of the tensor)")
print(f"Element size: {zeros_like.element_size()} bytes (Size of each element)")

Zeros tensor:
tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])
Diension: 2
Shape: torch.Size([4, 2]) (Dimensions of the tensor)
Element size: 4 bytes (Size of each element)


In [21]:
ones_like: torch.Tensor = torch.ones_like(input=sample)
print(f"Ones tensor:\n{ones_like}")
print(f"Diension: {ones_like.ndim}")
print(f"Shape: {ones_like.shape} (Dimensions of the tensor)")
print(f"Element size: {ones_like.element_size()} bytes (Size of each element)")

Ones tensor:
tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])
Diension: 2
Shape: torch.Size([4, 2]) (Dimensions of the tensor)
Element size: 4 bytes (Size of each element)


**8. Eye Tensor**

In [23]:
eye_tensor: torch.Tensor = torch.eye(n=5)
print(f"Eye Tensor:\n{eye_tensor}")
print(f"Diension: {ones_like.ndim}")
print(f"Shape: {eye_tensor.shape} (Dimensions of the tensor)")
print(f"Element size: {eye_tensor.element_size()} bytes (Size of each element)")

Eye Tensor:
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
Diension: 2
Shape: torch.Size([5, 5]) (Dimensions of the tensor)
Element size: 4 bytes (Size of each element)


**9. Full Tensor**

In [24]:
full_tensor: torch.Tensor = torch.full(size=(3, 4), fill_value=8)
print(f"Full tensor:\n{full_tensor}")
print(f"Diension: {ones_like.ndim}")
print(f"Shape: {full_tensor.shape} (Dimensions of the tensor)")
print(f"Element size: {full_tensor.element_size()} bytes (Size of each element)")

Full tensor:
tensor([[8, 8, 8, 8],
        [8, 8, 8, 8],
        [8, 8, 8, 8]])
Diension: 2
Shape: torch.Size([3, 4]) (Dimensions of the tensor)
Element size: 8 bytes (Size of each element)


**10. Linspace**

In [25]:
x: torch.Tensor = torch.linspace(start=0, end=10, steps=5)
print(x)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])


# Torch Data Types

In [29]:
sample: torch.Tensor = torch.rand(size=(4, 2))
print(f"Sample tensor:\n{sample}")
print(f"Data type: {sample.dtype}")
print(f"Element size: {sample.element_size()} bytes (Size of each element)")

Sample tensor:
tensor([[0.3853, 0.9431],
        [0.6344, 0.1645],
        [0.5927, 0.4712],
        [0.1956, 0.7791]])
Data type: torch.float32
Element size: 4 bytes (Size of each element)


In [30]:
sample: torch.Tensor = torch.rand(size=(4, 2), dtype=torch.float16)
print(f"Sample tensor:\n{sample}")
print(f"Data type: {sample.dtype}")
print(f"Element size: {sample.element_size()} bytes (Size of each element)")

Sample tensor:
tensor([[0.0371, 0.2705],
        [0.8477, 0.8530],
        [0.9673, 0.2808],
        [0.1572, 0.2422]], dtype=torch.float16)
Data type: torch.float16
Element size: 2 bytes (Size of each element)


In [31]:
sample: torch.Tensor = torch.rand(size=(4, 2), dtype=torch.float64)
print(f"Sample tensor:\n{sample}")
print(f"Data type: {sample.dtype}")
print(f"Element size: {sample.element_size()} bytes (Size of each element)")

Sample tensor:
tensor([[0.0368, 0.9370],
        [0.7524, 0.2547],
        [0.7730, 0.8342],
        [0.5603, 0.7122]], dtype=torch.float64)
Data type: torch.float64
Element size: 8 bytes (Size of each element)


**1. Change Data Type**

In [33]:
x: torch.Tensor = torch.arange(start=0, end=10, step=1)
print(x)
print(x.dtype)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.int64


In [35]:
x: torch.Tensor = x.type(dtype=torch.float32)
print(x)
print(x.dtype)

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])
torch.float32


## Getting information about a tensor
1. **Shape**
2. **Dtype**
3. **Device**

In [37]:
some_tensor: torch.Tensor = torch.rand(size=(3, 4))
print(f"Some tensor:\n{some_tensor}")
print(f"Shape: {some_tensor.shape}")
print(f"Dtype: {some_tensor.dtype}")
print(f"Device: {some_tensor.device}")

Some tensor:
tensor([[0.8568, 0.2853, 0.6356, 0.4534],
        [0.4567, 0.5824, 0.8492, 0.0154],
        [0.1801, 0.3131, 0.2498, 0.1441]])
Shape: torch.Size([3, 4])
Dtype: torch.float32
Device: cpu


## Tensor Operations (Manipulate Tensors)
1. **Addition**
2. **Subtraction**
3. **Multiplication**
4. **Division**
5. **Dot Product**
6. **Transpose**
7. **Matrix Multiplication**

In [38]:
# Addition of Tensors
a: torch.Tensor = torch.tensor(data=[1, 2, 3])
b: torch.Tensor = torch.tensor(data=[4, 5, 6])
c: torch.Tensor = a + b
print(c)
print(c.dtype)
print(c.shape)
print(c.device)

tensor([5, 7, 9])
torch.int64
torch.Size([3])
cpu


In [41]:
# Subraction of Tensors
a: torch.Tensor = torch.tensor(data=[1, 2, 3])
b: torch.Tensor = torch.tensor(data=[4, 5, 6])
c: torch.Tensor = a - b
print(c)
print(c.dtype)
print(c.shape)
print(c.device)

tensor([-3, -3, -3])
torch.int64
torch.Size([3])
cpu


In [45]:
# Multiplication of Tensors
a: torch.Tensor = torch.tensor(data=[1, 2, 3])
b: torch.Tensor = torch.tensor(data=[4, 5, 6])
c: torch.Tensor = a * b
print(c)
print(c.dtype)
print(c.shape)
print(c.device)

tensor([ 4, 10, 18])
torch.int64
torch.Size([3])
cpu


In [42]:
# Division of Tensors
a: torch.Tensor = torch.tensor(data=[1, 2, 3])
b: torch.Tensor = torch.tensor(data=[4, 5, 6])
c: torch.Tensor = a / b
print(c)
print(c.dtype)
print(c.shape)
print(c.device)

tensor([0.2500, 0.4000, 0.5000])
torch.float32
torch.Size([3])
cpu


In [43]:
# Dot Product of Tensors
a: torch.Tensor = torch.tensor(data=[1, 2, 3])
b: torch.Tensor = torch.tensor(data=[4, 5, 6])
c: torch.Tensor = torch.dot(input=a, tensor=b)
print(c)
print(c.dtype)
print(c.shape)
print(c.device)

tensor(32)
torch.int64
torch.Size([])
cpu


In [44]:
# Transpose of Tensors
a: torch.Tensor = torch.tensor(data=[[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b: torch.Tensor = torch.transpose(input=a, dim0=0, dim1=1)
print(a)
print(b)
print(b.dtype)
print(b.shape)
print(b.device)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])
torch.int64
torch.Size([3, 3])
cpu
