# Introduction to Tensors

In [56]:
import torch

print(torch.__version__)

2.2.2


**1. Scalar**

In [57]:
scalar: torch.Tensor = torch.tensor(data=8)

In [58]:
print(f"Scalar tensor: {scalar}")
print(f"Number of dimensions: {scalar.ndim} (0D tensor)")
print(f"Shape: {scalar.shape} (No dimensions for a scalar)")
print(f"Scalar value: {scalar.item()} (Extracted value)")
print(f"Element size: {scalar.element_size()} bytes (size of one element)")

Scalar tensor: 8
Number of dimensions: 0 (0D tensor)
Shape: torch.Size([]) (No dimensions for a scalar)
Scalar value: 8 (Extracted value)
Element size: 8 bytes (size of one element)


**2. Vector**

In [59]:
vector: torch.Tensor = torch.tensor(data=[8, 5])

In [60]:
print(f"Vector tensor: {vector}")
print(f"Number of dimensions: {vector.ndim} (1D tensor)")
print(f"Shape: {vector.shape} (Number of elements)")
print(f"Element size: {vector.element_size()} bytes (size of one element)")

Vector tensor: tensor([8, 5])
Number of dimensions: 1 (1D tensor)
Shape: torch.Size([2]) (Number of elements)
Element size: 8 bytes (size of one element)


**3. Matrix**

In [61]:
matrix: torch.Tensor = torch.tensor(data=[[1, 2], [3, 4], [4, 5]])

In [62]:
print(f"Matrix tensor:\n{matrix}")
print(f"Number of dimensions: {matrix.ndim} (2D tensor)")
print(f"Shape: {matrix.shape} (Rows, Columns)")
print(f"Element size: {matrix.element_size()} bytes (size of one element)")

Matrix tensor:
tensor([[1, 2],
        [3, 4],
        [4, 5]])
Number of dimensions: 2 (2D tensor)
Shape: torch.Size([3, 2]) (Rows, Columns)
Element size: 8 bytes (size of one element)


**4. Tensor**

In [65]:
tensor: torch.Tensor = torch.tensor(data=[[[1, 2, 3, 4], [3, 2, 1, 0], [4, 5, 6, 5]]])

In [66]:
print(f"Tensor:\n{tensor}")
print(f"Number of dimensions: {tensor.ndim} (Tensor rank)")
print(f"Shape: {tensor.shape} (Dimensions of the tensor)")
print(f"Element size: {tensor.element_size()} bytes (Size of each element)")

Tensor:
tensor([[[1, 2, 3, 4],
         [3, 2, 1, 0],
         [4, 5, 6, 5]]])
Number of dimensions: 3 (Tensor rank)
Shape: torch.Size([1, 3, 4]) (Dimensions of the tensor)
Element size: 8 bytes (Size of each element)


**5. Random Tensors**

In [68]:
random_tensor: torch.Tensor = torch.rand(size=(3, 4))
print(f"Random tensor:\n{random_tensor}")

Random tensor:
tensor([[0.2135, 0.2996, 0.4897, 0.3322],
        [0.3408, 0.5064, 0.7087, 0.1113],
        [0.0736, 0.0761, 0.3817, 0.0267]])


**6. Zeros and Ones**

In [71]:
zeros: torch.Tensor = torch.zeros(size=(3, 4))
print(f"Zeros tensor:\n{zeros}")

Zeros tensor:
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [73]:
ones: torch.Tensor = torch.ones(size=(3, 4))
print(f"Ones tensor:\n{ones}")

Ones tensor:
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


**7. Arange and Tensor Like**

In [75]:
x: torch.Tensor = torch.arange(start=0, end=10, step=1)
print(x)
y: torch.Tensor = torch.arange(start=0, end=10, step=2)
print(y)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 2, 4, 6, 8])


In [78]:
sample: torch.Tensor = torch.rand(size=(4, 2))
print(f"Sample tensor:\n{sample}")
print(f"Number of dimensions: {sample.ndim} (Tensor rank)")
print(f"Shape: {sample.shape} (Dimensions of the tensor)")
print(f"Element size: {sample.element_size()} bytes (Size of each element)")

Sample tensor:
tensor([[0.2581, 0.2070],
        [0.1650, 0.2945],
        [0.7664, 0.8781],
        [0.5916, 0.6157]])
Number of dimensions: 2 (Tensor rank)
Shape: torch.Size([4, 2]) (Dimensions of the tensor)
Element size: 4 bytes (Size of each element)


In [80]:
zeros_like = torch.zeros_like(input=sample)
print(f"Zeros tensor:\n{zeros_like}")
print(f"Element size: {zeros_like.element_size()} bytes (Size of each element)")
print(f"Shape: {zeros_like.shape} (Dimensions of the tensor)")
print(f"Element size: {zeros_like.element_size()} bytes (Size of each element)")

Zeros tensor:
tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])
Element size: 4 bytes (Size of each element)
Shape: torch.Size([4, 2]) (Dimensions of the tensor)
Element size: 4 bytes (Size of each element)
