# Introduction to Tensors

In [261]:
import torch

print(torch.__version__)

2.2.2


**1. Scalar**

In [262]:
scalar: torch.Tensor = torch.tensor(data=8)

In [263]:
print(f"Scalar tensor: {scalar}")
print(f"Number of dimensions: {scalar.ndim} (0D tensor)")
print(f"Shape: {scalar.shape} (No dimensions for a scalar)")
print(f"Scalar value: {scalar.item()} (Extracted value)")
print(f"Element size: {scalar.element_size()} bytes (size of one element)")

Scalar tensor: 8
Number of dimensions: 0 (0D tensor)
Shape: torch.Size([]) (No dimensions for a scalar)
Scalar value: 8 (Extracted value)
Element size: 8 bytes (size of one element)


**2. Vector**

In [264]:
vector: torch.Tensor = torch.tensor(data=[8, 5])

In [265]:
print(f"Vector tensor: {vector}")
print(f"Number of dimensions: {vector.ndim} (1D tensor)")
print(f"Shape: {vector.shape} (Number of elements)")
print(f"Element size: {vector.element_size()} bytes (size of one element)")

Vector tensor: tensor([8, 5])
Number of dimensions: 1 (1D tensor)
Shape: torch.Size([2]) (Number of elements)
Element size: 8 bytes (size of one element)


**3. Matrix**

In [266]:
matrix: torch.Tensor = torch.tensor(data=[[1, 2], [3, 4], [4, 5]])

In [267]:
print(f"Matrix tensor:\n{matrix}")
print(f"Number of dimensions: {matrix.ndim} (2D tensor)")
print(f"Shape: {matrix.shape} (Rows, Columns)")
print(f"Element size: {matrix.element_size()} bytes (size of one element)")

Matrix tensor:
tensor([[1, 2],
        [3, 4],
        [4, 5]])
Number of dimensions: 2 (2D tensor)
Shape: torch.Size([3, 2]) (Rows, Columns)
Element size: 8 bytes (size of one element)


**4. Tensor**

In [268]:
tensor: torch.Tensor = torch.tensor(data=[[[1, 2, 3, 4], [3, 2, 1, 0], [4, 5, 6, 5]]])

In [269]:
print(f"Tensor:\n{tensor}")
print(f"Number of dimensions: {tensor.ndim} (Tensor rank)")
print(f"Shape: {tensor.shape} (Dimensions of the tensor)")
print(f"Element size: {tensor.element_size()} bytes (Size of each element)")

Tensor:
tensor([[[1, 2, 3, 4],
         [3, 2, 1, 0],
         [4, 5, 6, 5]]])
Number of dimensions: 3 (Tensor rank)
Shape: torch.Size([1, 3, 4]) (Dimensions of the tensor)
Element size: 8 bytes (Size of each element)


**5. Random Tensors**

In [270]:
random_tensor: torch.Tensor = torch.rand(size=(3, 4))
print(f"Random tensor:\n{random_tensor}")

Random tensor:
tensor([[0.8427, 0.0799, 0.4284, 0.6844],
        [0.8967, 0.4371, 0.4546, 0.9459],
        [0.3249, 0.5713, 0.7443, 0.3238]])


**6. Zeros and Ones**

In [271]:
zeros: torch.Tensor = torch.zeros(size=(3, 4))
print(f"Zeros tensor:\n{zeros}")

Zeros tensor:
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [272]:
ones: torch.Tensor = torch.ones(size=(3, 4))
print(f"Ones tensor:\n{ones}")

Ones tensor:
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


**7. Arange and Tensor Like**

In [273]:
x: torch.Tensor = torch.arange(start=0, end=10, step=1)
print(x)
y: torch.Tensor = torch.arange(start=0, end=10, step=2)
print(y)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 2, 4, 6, 8])


In [274]:
sample: torch.Tensor = torch.rand(size=(4, 2))
print(f"Sample tensor:\n{sample}")
print(f"Number of dimensions: {sample.ndim} (Tensor rank)")
print(f"Shape: {sample.shape} (Dimensions of the tensor)")
print(f"Element size: {sample.element_size()} bytes (Size of each element)")

Sample tensor:
tensor([[0.3962, 0.8188],
        [0.7296, 0.7116],
        [0.2970, 0.0114],
        [0.8165, 0.3577]])
Number of dimensions: 2 (Tensor rank)
Shape: torch.Size([4, 2]) (Dimensions of the tensor)
Element size: 4 bytes (Size of each element)


In [275]:
zeros_like: torch.Tensor = torch.zeros_like(input=sample)
print(f"Zeros tensor:\n{zeros_like}")
print(f"Diension: {zeros_like.ndim}")
print(f"Shape: {zeros_like.shape} (Dimensions of the tensor)")
print(f"Element size: {zeros_like.element_size()} bytes (Size of each element)")

Zeros tensor:
tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])
Diension: 2
Shape: torch.Size([4, 2]) (Dimensions of the tensor)
Element size: 4 bytes (Size of each element)


In [276]:
ones_like: torch.Tensor = torch.ones_like(input=sample)
print(f"Ones tensor:\n{ones_like}")
print(f"Diension: {ones_like.ndim}")
print(f"Shape: {ones_like.shape} (Dimensions of the tensor)")
print(f"Element size: {ones_like.element_size()} bytes (Size of each element)")

Ones tensor:
tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])
Diension: 2
Shape: torch.Size([4, 2]) (Dimensions of the tensor)
Element size: 4 bytes (Size of each element)


**8. Eye Tensor**

In [277]:
eye_tensor: torch.Tensor = torch.eye(n=5)
print(f"Eye Tensor:\n{eye_tensor}")
print(f"Diension: {ones_like.ndim}")
print(f"Shape: {eye_tensor.shape} (Dimensions of the tensor)")
print(f"Element size: {eye_tensor.element_size()} bytes (Size of each element)")

Eye Tensor:
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
Diension: 2
Shape: torch.Size([5, 5]) (Dimensions of the tensor)
Element size: 4 bytes (Size of each element)


**9. Full Tensor**

In [278]:
full_tensor: torch.Tensor = torch.full(size=(3, 4), fill_value=8)
print(f"Full tensor:\n{full_tensor}")
print(f"Diension: {ones_like.ndim}")
print(f"Shape: {full_tensor.shape} (Dimensions of the tensor)")
print(f"Element size: {full_tensor.element_size()} bytes (Size of each element)")

Full tensor:
tensor([[8, 8, 8, 8],
        [8, 8, 8, 8],
        [8, 8, 8, 8]])
Diension: 2
Shape: torch.Size([3, 4]) (Dimensions of the tensor)
Element size: 8 bytes (Size of each element)


**10. Linspace**

In [279]:
x: torch.Tensor = torch.linspace(start=0, end=10, steps=5)
print(x)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])


# Torch Data Types

In [280]:
sample: torch.Tensor = torch.rand(size=(4, 2))
print(f"Sample tensor:\n{sample}")
print(f"Data type: {sample.dtype}")
print(f"Element size: {sample.element_size()} bytes (Size of each element)")

Sample tensor:
tensor([[0.9220, 0.5833],
        [0.3233, 0.3435],
        [0.8591, 0.9282],
        [0.3965, 0.2824]])
Data type: torch.float32
Element size: 4 bytes (Size of each element)


In [281]:
sample: torch.Tensor = torch.rand(size=(4, 2), dtype=torch.float16)
print(f"Sample tensor:\n{sample}")
print(f"Data type: {sample.dtype}")
print(f"Element size: {sample.element_size()} bytes (Size of each element)")

Sample tensor:
tensor([[0.2593, 0.5083],
        [0.4434, 0.2593],
        [0.7832, 0.1909],
        [0.2202, 0.6514]], dtype=torch.float16)
Data type: torch.float16
Element size: 2 bytes (Size of each element)


In [282]:
sample: torch.Tensor = torch.rand(size=(4, 2), dtype=torch.float64)
print(f"Sample tensor:\n{sample}")
print(f"Data type: {sample.dtype}")
print(f"Element size: {sample.element_size()} bytes (Size of each element)")

Sample tensor:
tensor([[0.4493, 0.5308],
        [0.1161, 0.0749],
        [0.9563, 0.0273],
        [0.4640, 0.8120]], dtype=torch.float64)
Data type: torch.float64
Element size: 8 bytes (Size of each element)


**1. Change Data Type**

In [283]:
x: torch.Tensor = torch.arange(start=0, end=10, step=1)
print(x)
print(x.dtype)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.int64


In [284]:
x: torch.Tensor = x.type(dtype=torch.float32)
print(x)
print(x.dtype)

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])
torch.float32


## Getting information about a tensor
1. **Shape**
2. **Dtype**
3. **Device**

In [285]:
some_tensor: torch.Tensor = torch.rand(size=(3, 4))
print(f"Some tensor:\n{some_tensor}")
print(f"Shape: {some_tensor.shape}")
print(f"Dtype: {some_tensor.dtype}")
print(f"Device: {some_tensor.device}")

Some tensor:
tensor([[0.6463, 0.0813, 0.8076, 0.1664],
        [0.5836, 0.5651, 0.1130, 0.2998],
        [0.8901, 0.1879, 0.3961, 0.4410]])
Shape: torch.Size([3, 4])
Dtype: torch.float32
Device: cpu


## Tensor Operations (Manipulate Tensors)
1. **Addition**
2. **Subtraction**
3. **Multiplication**
4. **Division**
5. **Dot Product**
6. **Transpose**
7. **Matrix Multiplication**

In [286]:
# Addition of Tensors
a: torch.Tensor = torch.tensor(data=[1, 2, 3])
b: torch.Tensor = torch.tensor(data=[4, 5, 6])
c: torch.Tensor = a + b
print(c)
print(c.dtype)
print(c.shape)
print(c.device)

tensor([5, 7, 9])
torch.int64
torch.Size([3])
cpu


In [287]:
# Subraction of Tensors
a: torch.Tensor = torch.tensor(data=[1, 2, 3])
b: torch.Tensor = torch.tensor(data=[4, 5, 6])
c: torch.Tensor = a - b
print(c)
print(c.dtype)
print(c.shape)
print(c.device)

tensor([-3, -3, -3])
torch.int64
torch.Size([3])
cpu


In [288]:
# Multiplication of Tensors
a: torch.Tensor = torch.tensor(data=[1, 2, 3])
b: torch.Tensor = torch.tensor(data=[4, 5, 6])
c: torch.Tensor = a * b
print(c)
print(c.dtype)
print(c.shape)
print(c.device)

tensor([ 4, 10, 18])
torch.int64
torch.Size([3])
cpu


In [289]:
# Division of Tensors
a: torch.Tensor = torch.tensor(data=[1, 2, 3])
b: torch.Tensor = torch.tensor(data=[4, 5, 6])
c: torch.Tensor = a / b
print(c)
print(c.dtype)
print(c.shape)
print(c.device)

tensor([0.2500, 0.4000, 0.5000])
torch.float32
torch.Size([3])
cpu


In [290]:
# Dot Product of Tensors
a: torch.Tensor = torch.tensor(data=[1, 2, 3])
b: torch.Tensor = torch.tensor(data=[4, 5, 6])
c: torch.Tensor = torch.dot(input=a, tensor=b)
print(c)
print(c.dtype)
print(c.shape)
print(c.device)

tensor(32)
torch.int64
torch.Size([])
cpu


In [291]:
# Transpose of Tensors
a: torch.Tensor = torch.tensor(data=[[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b: torch.Tensor = torch.transpose(input=a, dim0=0, dim1=1)
print(a)
print(f"Transpose: \n{a.T}")
print(b)
print(f"Transpose: \n{b.T}")
print(b.dtype)
print(b.shape)
print(b.device)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Transpose: 
tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])
tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])
Transpose: 
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
torch.int64
torch.Size([3, 3])
cpu


## Find min, max , mean, sum , etc in Tensors

In [292]:
x: torch.Tensor = torch.arange(start=0, end=10, step=1, dtype=torch.float32)
print(f"X: {x}")

print(f"Min: {x.min()}")
print(f"Max: {x.max()}")
print(f"Mean: {x.mean()}")
print(f"Sum: {x.sum()}")

X: tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])
Min: 0.0
Max: 9.0
Mean: 4.5
Sum: 45.0


## Positional Min and Max

In [293]:
sample: torch.Tensor = torch.arange(start=0, end=20, step=2, dtype=torch.float32)

print(sample)
print(f"Min: {sample.min()}")
print(f"Argmin: {sample.argmin()}")
print(f"Max: {sample.max()}")
print(f"Argmax: {sample.argmax()}")

tensor([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])
Min: 0.0
Argmin: 0
Max: 18.0
Argmax: 9


## Tensor Reshaping, Stacking, Squeezing, UnSqueezing, Permuting

In [294]:
x: torch.Tensor = torch.arange(start=0, end=50, step=1, dtype=torch.float32)
print(f"X: {x}")

X: tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26., 27.,
        28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39., 40., 41.,
        42., 43., 44., 45., 46., 47., 48., 49.])


In [295]:
# Reshape
x.reshape(2, 25)

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
         14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.],
        [25., 26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
         39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49.]])

In [296]:
# Reshape
x.reshape(5, 5, 2)

tensor([[[ 0.,  1.],
         [ 2.,  3.],
         [ 4.,  5.],
         [ 6.,  7.],
         [ 8.,  9.]],

        [[10., 11.],
         [12., 13.],
         [14., 15.],
         [16., 17.],
         [18., 19.]],

        [[20., 21.],
         [22., 23.],
         [24., 25.],
         [26., 27.],
         [28., 29.]],

        [[30., 31.],
         [32., 33.],
         [34., 35.],
         [36., 37.],
         [38., 39.]],

        [[40., 41.],
         [42., 43.],
         [44., 45.],
         [46., 47.],
         [48., 49.]]])

In [297]:
y: torch.Tensor = torch.arange(start=0, end=50, step=1, dtype=torch.float32)
print(f"Y: {y}")
print(f"Shape: {y.shape}")

Y: tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26., 27.,
        28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39., 40., 41.,
        42., 43., 44., 45., 46., 47., 48., 49.])
Shape: torch.Size([50])


In [298]:
y_view: torch.Tensor = y.view(5, 5, 2)
print(f"View: {y_view}")
print(f"Shape: {y_view.shape}")

View: tensor([[[ 0.,  1.],
         [ 2.,  3.],
         [ 4.,  5.],
         [ 6.,  7.],
         [ 8.,  9.]],

        [[10., 11.],
         [12., 13.],
         [14., 15.],
         [16., 17.],
         [18., 19.]],

        [[20., 21.],
         [22., 23.],
         [24., 25.],
         [26., 27.],
         [28., 29.]],

        [[30., 31.],
         [32., 33.],
         [34., 35.],
         [36., 37.],
         [38., 39.]],

        [[40., 41.],
         [42., 43.],
         [44., 45.],
         [46., 47.],
         [48., 49.]]])
Shape: torch.Size([5, 5, 2])


In [299]:
y_view[2, 1, 1] = 100
print(f"View: {y_view}")
print(f"Shape: {y_view.shape}")
print(f"Y: {y}")

View: tensor([[[  0.,   1.],
         [  2.,   3.],
         [  4.,   5.],
         [  6.,   7.],
         [  8.,   9.]],

        [[ 10.,  11.],
         [ 12.,  13.],
         [ 14.,  15.],
         [ 16.,  17.],
         [ 18.,  19.]],

        [[ 20.,  21.],
         [ 22., 100.],
         [ 24.,  25.],
         [ 26.,  27.],
         [ 28.,  29.]],

        [[ 30.,  31.],
         [ 32.,  33.],
         [ 34.,  35.],
         [ 36.,  37.],
         [ 38.,  39.]],

        [[ 40.,  41.],
         [ 42.,  43.],
         [ 44.,  45.],
         [ 46.,  47.],
         [ 48.,  49.]]])
Shape: torch.Size([5, 5, 2])
Y: tensor([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
         12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22., 100.,
         24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,  34.,  35.,
         36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,  45.,  46.,  47.,
         48.,  49.])


In [300]:
y

tensor([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
         12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22., 100.,
         24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,  34.,  35.,
         36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,  45.,  46.,  47.,
         48.,  49.])

In [301]:
# Torch Stack
tensor: torch.Tensor = torch.arange(start=0, end=50, step=10, dtype=torch.float32)
print(f"Tensor: {tensor}")
print(f"Tensor shape: {tensor.shape}")
print(f"Dimensions: {tensor.ndim}")

Tensor: tensor([ 0., 10., 20., 30., 40.])
Tensor shape: torch.Size([5])
Dimensions: 1


In [302]:
tensor_stacked: torch.Tensor = torch.stack(tensors=[tensor, tensor, tensor], dim=0)
print(f"Stacked: {tensor_stacked}")
print(f"Stacked shape: {tensor_stacked.shape}")
print(f"Dimensions: {tensor_stacked.ndim}")

Stacked: tensor([[ 0., 10., 20., 30., 40.],
        [ 0., 10., 20., 30., 40.],
        [ 0., 10., 20., 30., 40.]])
Stacked shape: torch.Size([3, 5])
Dimensions: 2


In [303]:
tensor_stacked: torch.Tensor = torch.stack(tensors=[tensor, tensor, tensor], dim=1)
print(f"Stacked: {tensor_stacked}")
print(f"Stacked shape: {tensor_stacked.shape}")
print(f"Dimensions: {tensor_stacked.ndim}")


Stacked: tensor([[ 0.,  0.,  0.],
        [10., 10., 10.],
        [20., 20., 20.],
        [30., 30., 30.],
        [40., 40., 40.]])
Stacked shape: torch.Size([5, 3])
Dimensions: 2


In [304]:
# Torch Unsqueeze: This is used to add a dimension to a tensor at the specified index (0 or 1)
x: torch.Tensor = torch.arange(start=0, end=10, step=1, dtype=torch.float32)
print(f"X: {x}")
print(f"X shape: {x.shape}")
print(f"Dimensions: {x.ndim}")
x_unsqueezed: torch.Tensor = x.unsqueeze(dim=0)
print(f"Unsqueezed shape: {x_unsqueezed.shape}")
print(f"Unsqueezed @ Dim 0: {x_unsqueezed}")
print(f"Dimensions: {x_unsqueezed.ndim}")
x_unsqueezed: torch.Tensor = x.unsqueeze(dim=1)
print(f"Unsqueezed shape: {x_unsqueezed.shape}")
print(f"Unsqueezed @ Dim 1: {x_unsqueezed}")
print(f"Dimensions: {x_unsqueezed.ndim}")

X: tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])
X shape: torch.Size([10])
Dimensions: 1
Unsqueezed shape: torch.Size([1, 10])
Unsqueezed @ Dim 0: tensor([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]])
Dimensions: 2
Unsqueezed shape: torch.Size([10, 1])
Unsqueezed @ Dim 1: tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
Dimensions: 2


In [305]:
# Torch Squeeze: This is used to remove the one dimension from a tensor at the specified index (0 or 1)
x: torch.Tensor = torch.rand(size=(1, 4), dtype=torch.float32)
print(f"X: {x}")
print(f"X shape: {x.shape}")
print(f"Dimensions: {x.ndim}")

x_squeezed: torch.Tensor = x.squeeze(dim=0)
print(f"Squeezed shape: {x_squeezed.shape}")
print(f"Squeezed @ Dim 0: {x_squeezed}")

X: tensor([[0.3845, 0.4929, 0.9792, 0.7224]])
X shape: torch.Size([1, 4])
Dimensions: 2
Squeezed shape: torch.Size([4])
Squeezed @ Dim 0: tensor([0.3845, 0.4929, 0.9792, 0.7224])


In [306]:
# Torch Squeeze: This is used to remove the one dimension from a tensor at the specified index (0 or 1)
x: torch.Tensor = torch.rand(size=(4, 1), dtype=torch.float32)
print(f"X: {x}")
print(f"X shape: {x.shape}")
print(f"Dimensions: {x.ndim}")

x_squeezed: torch.Tensor = x.squeeze(dim=1)
print(f"Squeezed shape: {x_squeezed.shape}")
print(f"Squeezed @ Dim 0: {x_squeezed}")

X: tensor([[0.8213],
        [0.1347],
        [0.0907],
        [0.5213]])
X shape: torch.Size([4, 1])
Dimensions: 2
Squeezed shape: torch.Size([4])
Squeezed @ Dim 0: tensor([0.8213, 0.1347, 0.0907, 0.5213])


## Permute

Rearrange tensor dimensions from (a, b, c, d) to (b, a, c, d) or (b, d, a, c) or any other order.

In [307]:
x: torch.Tensor = torch.randn(size=(2, 4), dtype=torch.float32)
print(f"X: \n{x}")
print(f"X shape: {x.shape}")
print(f"Dimensions: {x.ndim}")

X: 
tensor([[ 0.4104,  1.9645, -0.7227, -0.1388],
        [ 1.2633, -0.0564,  0.5764,  0.3185]])
X shape: torch.Size([2, 4])
Dimensions: 2


In [308]:
x_permuted: torch.Tensor = x.permute(1, 0)
print(f"Permuted: \n{x_permuted}")
print(f"Permuted shape: {x_permuted.shape}")
print(f"Dimensions: {x_permuted.ndim}")

Permuted: 
tensor([[ 0.4104,  1.2633],
        [ 1.9645, -0.0564],
        [-0.7227,  0.5764],
        [-0.1388,  0.3185]])
Permuted shape: torch.Size([4, 2])
Dimensions: 2


In [309]:
x: torch.Tensor = torch.randn(size=(2, 4, 3), dtype=torch.float32)
print(f"X: \n{x}")
print(f"X shape: {x.shape}")
print(f"Dimensions: {x.ndim}")

x_permuted: torch.Tensor = x.permute(1, 2, 0)
print(f"Permuted: \n{x_permuted}")
print(f"Permuted shape: {x_permuted.shape}")
print(f"Dimensions: {x_permuted.ndim}")

X: 
tensor([[[ 0.5759, -1.1607,  1.1027],
         [-1.7399,  0.8367,  0.0463],
         [-0.2827,  0.7077,  0.1904],
         [ 1.0056, -0.3175, -0.2409]],

        [[ 1.3167,  0.4540,  0.0246],
         [-0.3806, -1.1052,  2.6606],
         [-1.3440,  1.5551, -2.0453],
         [-0.5887, -0.9425, -1.1497]]])
X shape: torch.Size([2, 4, 3])
Dimensions: 3
Permuted: 
tensor([[[ 0.5759,  1.3167],
         [-1.1607,  0.4540],
         [ 1.1027,  0.0246]],

        [[-1.7399, -0.3806],
         [ 0.8367, -1.1052],
         [ 0.0463,  2.6606]],

        [[-0.2827, -1.3440],
         [ 0.7077,  1.5551],
         [ 0.1904, -2.0453]],

        [[ 1.0056, -0.5887],
         [-0.3175, -0.9425],
         [-0.2409, -1.1497]]])
Permuted shape: torch.Size([4, 3, 2])
Dimensions: 3


## Tensors Indexing

In [310]:
x: torch.Tensor = torch.arange(start=0, end=10, step=1, dtype=torch.float32).reshape(
    shape=(1, 2, 5)
)
print(f"X: \n{x}")
print(f"X shape: {x.shape}")

X: 
tensor([[[0., 1., 2., 3., 4.],
         [5., 6., 7., 8., 9.]]])
X shape: torch.Size([1, 2, 5])


In [311]:
x[0]

tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]])

In [312]:
x[0, 0, 1]

tensor(1.)

## PyTorch and NumPy

In [321]:
import numpy as np

In [327]:
array: np.ndarray = np.arange(start=0, stop=10, step=1, dtype=np.float32)
print(f"Array: \n{array}")

Array: 
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


## Reproducibility

In [329]:
random_tensor: torch.Tensor = torch.rand(size=(3, 4), dtype=torch.float32)
print(f"Random tensor: \n{random_tensor}")

Random tensor: 
tensor([[0.8934, 0.3433, 0.8815, 0.0231],
        [0.1120, 0.9955, 0.7101, 0.2445],
        [0.7027, 0.6008, 0.2284, 0.0852]])


In [330]:
random_tensor: torch.Tensor = torch.rand(size=(3, 4), dtype=torch.float32)
print(f"Random tensor: \n{random_tensor}")

Random tensor: 
tensor([[0.8167, 0.4155, 0.3893, 0.1586],
        [0.3620, 0.7613, 0.3083, 0.1497],
        [0.7130, 0.5706, 0.4787, 0.7841]])


In [331]:
random_seed = 44
torch.manual_seed(seed=random_seed)
random_tensor: torch.Tensor = torch.rand(size=(3, 4), dtype=torch.float32)
print(f"Random tensor: \n{random_tensor}")

Random tensor: 
tensor([[0.7196, 0.7307, 0.8278, 0.1343],
        [0.6280, 0.7297, 0.2882, 0.2112],
        [0.9836, 0.8722, 0.9650, 0.7837]])


In [333]:
torch.manual_seed(seed=random_seed)
random_tensor: torch.Tensor = torch.rand(size=(3, 4), dtype=torch.float32)
print(f"Random tensor: \n{random_tensor}")

Random tensor: 
tensor([[0.7196, 0.7307, 0.8278, 0.1343],
        [0.6280, 0.7297, 0.2882, 0.2112],
        [0.9836, 0.8722, 0.9650, 0.7837]])


# Working with GPUs.

In [334]:
torch.cuda.is_available()

False

In [347]:
# GPU / Device Agnostic Code
device = torch.device(device="cuda" if torch.cuda.is_available() else "cpu")
print(f"Device: {device}")

Device: cpu


In [348]:
# GPU Device Count
torch.cuda.device_count()
print(f"Device count: {torch.cuda.device_count()}")

Device count: 0


In [341]:
print(tensor, tensor.device)

tensor([ 0., 10., 20., 30., 40.]) cpu


In [343]:
tensor.to(device=device)
print(tensor, tensor.device)

tensor([ 0., 10., 20., 30., 40.]) cpu


In [345]:
tensor_gpu: torch.Tensor = tensor.to(device=device)
print(tensor_gpu, tensor_gpu.device)

tensor([ 0., 10., 20., 30., 40.]) cpu


In [346]:
tensor_cpu: torch.Tensor = tensor_gpu.cpu()
print(tensor_cpu, tensor_cpu.device)

tensor([ 0., 10., 20., 30., 40.]) cpu
